spring:
  http:
    gzip:
      mimeTypes: application/json
server:
  contextPath: /${spring.application.name}/v${spring.application.majorVersion}
  port: ${port:8180}
endpoints:
  health:
    sensitive: false
management:
  contextPath: /admin
  security:
    enabled: false
security:
  basic:
    enabled: false
info:
  build:
    artifact: 'simple-rest-app-with-discovery'
    name: 'OneWeb :: MBUSA Demo :: Simple REST App with discovery'
    description: 'Simple REST service application'
    version: '1.0.0-SNAPSHOT'
contact:
  name: Gregor Zurowski
  url: http://www.cinteo.com
  email: gregor@zurowski.net
